// nekop2p Protocol Buffers 定义
// 生成: protoc --go_out=. nekop2p.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: nekop2p.proto

package nekop2p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRole int32

const (
	NodeRole_NODE_NONE            NodeRole = 0
	NodeRole_NODE_PUBLIC          NodeRole = 1
	NodeRole_NODE_OFFICIAL_RELAY  NodeRole = 2
	NodeRole_NODE_OFFICIAL_RECORD NodeRole = 3
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_NONE",
		1: "NODE_PUBLIC",
		2: "NODE_OFFICIAL_RELAY",
		3: "NODE_OFFICIAL_RECORD",
	}
	NodeRole_value = map[string]int32{
		"NODE_NONE":            0,
		"NODE_PUBLIC":          1,
		"NODE_OFFICIAL_RELAY":  2,
		"NODE_OFFICIAL_RECORD": 3,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_nekop2p_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_nekop2p_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{0}
}

type BondStatus int32

const (
	BondStatus_BOND_ACTIVE    BondStatus = 0
	BondStatus_BOND_RELEASED  BondStatus = 1
	BondStatus_BOND_FORFEITED BondStatus = 2
)

// Enum value maps for BondStatus.
var (
	BondStatus_name = map[int32]string{
		0: "BOND_ACTIVE",
		1: "BOND_RELEASED",
		2: "BOND_FORFEITED",
	}
	BondStatus_value = map[string]int32{
		"BOND_ACTIVE":    0,
		"BOND_RELEASED":  1,
		"BOND_FORFEITED": 2,
	}
)

func (x BondStatus) Enum() *BondStatus {
	p := new(BondStatus)
	*p = x
	return p
}

func (x BondStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BondStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nekop2p_proto_enumTypes[1].Descriptor()
}

func (BondStatus) Type() protoreflect.EnumType {
	return &file_nekop2p_proto_enumTypes[1]
}

func (x BondStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BondStatus.Descriptor instead.
func (BondStatus) EnumDescriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{1}
}

type LoanStatus int32

const (
	LoanStatus_LOAN_PENDING   LoanStatus = 0
	LoanStatus_LOAN_ACTIVE    LoanStatus = 1
	LoanStatus_LOAN_SETTLED   LoanStatus = 2
	LoanStatus_LOAN_DEFAULTED LoanStatus = 3
)

// Enum value maps for LoanStatus.
var (
	LoanStatus_name = map[int32]string{
		0: "LOAN_PENDING",
		1: "LOAN_ACTIVE",
		2: "LOAN_SETTLED",
		3: "LOAN_DEFAULTED",
	}
	LoanStatus_value = map[string]int32{
		"LOAN_PENDING":   0,
		"LOAN_ACTIVE":    1,
		"LOAN_SETTLED":   2,
		"LOAN_DEFAULTED": 3,
	}
)

func (x LoanStatus) Enum() *LoanStatus {
	p := new(LoanStatus)
	*p = x
	return p
}

func (x LoanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nekop2p_proto_enumTypes[2].Descriptor()
}

func (LoanStatus) Type() protoreflect.EnumType {
	return &file_nekop2p_proto_enumTypes[2]
}

func (x LoanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoanStatus.Descriptor instead.
func (LoanStatus) EnumDescriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{2}
}

type ExamType int32

const (
	ExamType_EXAM_RELAY  ExamType = 0
	ExamType_EXAM_RECORD ExamType = 1
)

// Enum value maps for ExamType.
var (
	ExamType_name = map[int32]string{
		0: "EXAM_RELAY",
		1: "EXAM_RECORD",
	}
	ExamType_value = map[string]int32{
		"EXAM_RELAY":  0,
		"EXAM_RECORD": 1,
	}
)

func (x ExamType) Enum() *ExamType {
	p := new(ExamType)
	*p = x
	return p
}

func (x ExamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExamType) Descriptor() protoreflect.EnumDescriptor {
	return file_nekop2p_proto_enumTypes[3].Descriptor()
}

func (ExamType) Type() protoreflect.EnumType {
	return &file_nekop2p_proto_enumTypes[3]
}

func (x ExamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExamType.Descriptor instead.
func (ExamType) EnumDescriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{3}
}

type UserBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AccountNumber uint64                 `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	RecvPk        []byte                 `protobuf:"bytes,4,opt,name=recv_pk,json=recvPk,proto3" json:"recv_pk,omitempty"` // Curve25519
	SendPk        []byte                 `protobuf:"bytes,5,opt,name=send_pk,json=sendPk,proto3" json:"send_pk,omitempty"` // Ed25519
	CreditScore   uint64                 `protobuf:"varint,6,opt,name=credit_score,json=creditScore,proto3" json:"credit_score,omitempty"`
	TrustWeight   uint64                 `protobuf:"varint,7,opt,name=trust_weight,json=trustWeight,proto3" json:"trust_weight,omitempty"`
	TotalRepay    uint64                 `protobuf:"varint,8,opt,name=total_repay,json=totalRepay,proto3" json:"total_repay,omitempty"`
	CreditLimit   uint64                 `protobuf:"varint,9,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	SeedPhase     bool                   `protobuf:"varint,10,opt,name=seed_phase,json=seedPhase,proto3" json:"seed_phase,omitempty"`
	Guarantors    [][]byte               `protobuf:"bytes,11,rep,name=guarantors,proto3" json:"guarantors,omitempty"`
	NodeRole      NodeRole               `protobuf:"varint,12,opt,name=node_role,json=nodeRole,proto3,enum=nekop2p.NodeRole" json:"node_role,omitempty"`
	NodeTermStart int64                  `protobuf:"varint,13,opt,name=node_term_start,json=nodeTermStart,proto3" json:"node_term_start,omitempty"`
	NodeTermEnd   int64                  `protobuf:"varint,14,opt,name=node_term_end,json=nodeTermEnd,proto3" json:"node_term_end,omitempty"`
	Friends       []*FriendRecord        `protobuf:"bytes,15,rep,name=friends,proto3" json:"friends,omitempty"`
	GuaranteedOf  []*BondRef             `protobuf:"bytes,16,rep,name=guaranteed_of,json=guaranteedOf,proto3" json:"guaranteed_of,omitempty"`
	GuaranteedBy  []*BondRef             `protobuf:"bytes,17,rep,name=guaranteed_by,json=guaranteedBy,proto3" json:"guaranteed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBlock) Reset() {
	*x = UserBlock{}
	mi := &file_nekop2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBlock) ProtoMessage() {}

func (x *UserBlock) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBlock.ProtoReflect.Descriptor instead.
func (*UserBlock) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{0}
}

func (x *UserBlock) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserBlock) GetAccountNumber() uint64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UserBlock) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UserBlock) GetRecvPk() []byte {
	if x != nil {
		return x.RecvPk
	}
	return nil
}

func (x *UserBlock) GetSendPk() []byte {
	if x != nil {
		return x.SendPk
	}
	return nil
}

func (x *UserBlock) GetCreditScore() uint64 {
	if x != nil {
		return x.CreditScore
	}
	return 0
}

func (x *UserBlock) GetTrustWeight() uint64 {
	if x != nil {
		return x.TrustWeight
	}
	return 0
}

func (x *UserBlock) GetTotalRepay() uint64 {
	if x != nil {
		return x.TotalRepay
	}
	return 0
}

func (x *UserBlock) GetCreditLimit() uint64 {
	if x != nil {
		return x.CreditLimit
	}
	return 0
}

func (x *UserBlock) GetSeedPhase() bool {
	if x != nil {
		return x.SeedPhase
	}
	return false
}

func (x *UserBlock) GetGuarantors() [][]byte {
	if x != nil {
		return x.Guarantors
	}
	return nil
}

func (x *UserBlock) GetNodeRole() NodeRole {
	if x != nil {
		return x.NodeRole
	}
	return NodeRole_NODE_NONE
}

func (x *UserBlock) GetNodeTermStart() int64 {
	if x != nil {
		return x.NodeTermStart
	}
	return 0
}

func (x *UserBlock) GetNodeTermEnd() int64 {
	if x != nil {
		return x.NodeTermEnd
	}
	return 0
}

func (x *UserBlock) GetFriends() []*FriendRecord {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *UserBlock) GetGuaranteedOf() []*BondRef {
	if x != nil {
		return x.GuaranteedOf
	}
	return nil
}

func (x *UserBlock) GetGuaranteedBy() []*BondRef {
	if x != nil {
		return x.GuaranteedBy
	}
	return nil
}

type FriendRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	RecvPk        []byte                 `protobuf:"bytes,2,opt,name=recv_pk,json=recvPk,proto3" json:"recv_pk,omitempty"`
	SendPk        []byte                 `protobuf:"bytes,3,opt,name=send_pk,json=sendPk,proto3" json:"send_pk,omitempty"`
	TrustDist     uint32                 `protobuf:"varint,4,opt,name=trust_dist,json=trustDist,proto3" json:"trust_dist,omitempty"`
	AddedAt       int64                  `protobuf:"varint,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	IntroducedBy  []byte                 `protobuf:"bytes,6,opt,name=introduced_by,json=introducedBy,proto3" json:"introduced_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRecord) Reset() {
	*x = FriendRecord{}
	mi := &file_nekop2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRecord) ProtoMessage() {}

func (x *FriendRecord) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRecord.ProtoReflect.Descriptor instead.
func (*FriendRecord) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRecord) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *FriendRecord) GetRecvPk() []byte {
	if x != nil {
		return x.RecvPk
	}
	return nil
}

func (x *FriendRecord) GetSendPk() []byte {
	if x != nil {
		return x.SendPk
	}
	return nil
}

func (x *FriendRecord) GetTrustDist() uint32 {
	if x != nil {
		return x.TrustDist
	}
	return 0
}

func (x *FriendRecord) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *FriendRecord) GetIntroducedBy() []byte {
	if x != nil {
		return x.IntroducedBy
	}
	return nil
}

type BondRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BondId        string                 `protobuf:"bytes,1,opt,name=bond_id,json=bondId,proto3" json:"bond_id,omitempty"`
	OtherParty    []byte                 `protobuf:"bytes,2,opt,name=other_party,json=otherParty,proto3" json:"other_party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BondRef) Reset() {
	*x = BondRef{}
	mi := &file_nekop2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BondRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BondRef) ProtoMessage() {}

func (x *BondRef) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BondRef.ProtoReflect.Descriptor instead.
func (*BondRef) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{2}
}

func (x *BondRef) GetBondId() string {
	if x != nil {
		return x.BondId
	}
	return ""
}

func (x *BondRef) GetOtherParty() []byte {
	if x != nil {
		return x.OtherParty
	}
	return nil
}

type GuaranteeBond struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BondId            string                 `protobuf:"bytes,1,opt,name=bond_id,json=bondId,proto3" json:"bond_id,omitempty"`
	Inviter           []byte                 `protobuf:"bytes,2,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee           []byte                 `protobuf:"bytes,3,opt,name=invitee,proto3" json:"invitee,omitempty"`
	LockedCommitments [][]byte               `protobuf:"bytes,4,rep,name=locked_commitments,json=lockedCommitments,proto3" json:"locked_commitments,omitempty"`
	TotalBond         uint64                 `protobuf:"varint,5,opt,name=total_bond,json=totalBond,proto3" json:"total_bond,omitempty"`
	Coefficient       uint64                 `protobuf:"varint,6,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	SeedLimit         uint64                 `protobuf:"varint,7,opt,name=seed_limit,json=seedLimit,proto3" json:"seed_limit,omitempty"`
	LockedAt          int64                  `protobuf:"varint,8,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	UnlockAt          int64                  `protobuf:"varint,9,opt,name=unlock_at,json=unlockAt,proto3" json:"unlock_at,omitempty"`
	Status            BondStatus             `protobuf:"varint,10,opt,name=status,proto3,enum=nekop2p.BondStatus" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GuaranteeBond) Reset() {
	*x = GuaranteeBond{}
	mi := &file_nekop2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuaranteeBond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuaranteeBond) ProtoMessage() {}

func (x *GuaranteeBond) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuaranteeBond.ProtoReflect.Descriptor instead.
func (*GuaranteeBond) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{3}
}

func (x *GuaranteeBond) GetBondId() string {
	if x != nil {
		return x.BondId
	}
	return ""
}

func (x *GuaranteeBond) GetInviter() []byte {
	if x != nil {
		return x.Inviter
	}
	return nil
}

func (x *GuaranteeBond) GetInvitee() []byte {
	if x != nil {
		return x.Invitee
	}
	return nil
}

func (x *GuaranteeBond) GetLockedCommitments() [][]byte {
	if x != nil {
		return x.LockedCommitments
	}
	return nil
}

func (x *GuaranteeBond) GetTotalBond() uint64 {
	if x != nil {
		return x.TotalBond
	}
	return 0
}

func (x *GuaranteeBond) GetCoefficient() uint64 {
	if x != nil {
		return x.Coefficient
	}
	return 0
}

func (x *GuaranteeBond) GetSeedLimit() uint64 {
	if x != nil {
		return x.SeedLimit
	}
	return 0
}

func (x *GuaranteeBond) GetLockedAt() int64 {
	if x != nil {
		return x.LockedAt
	}
	return 0
}

func (x *GuaranteeBond) GetUnlockAt() int64 {
	if x != nil {
		return x.UnlockAt
	}
	return 0
}

func (x *GuaranteeBond) GetStatus() BondStatus {
	if x != nil {
		return x.Status
	}
	return BondStatus_BOND_ACTIVE
}

type LoanRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	BorrowerAnon  []byte                 `protobuf:"bytes,2,opt,name=borrower_anon,json=borrowerAnon,proto3" json:"borrower_anon,omitempty"`
	LenderAnon    []byte                 `protobuf:"bytes,3,opt,name=lender_anon,json=lenderAnon,proto3" json:"lender_anon,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TermDays      int64                  `protobuf:"varint,5,opt,name=term_days,json=termDays,proto3" json:"term_days,omitempty"`
	Status        LoanStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=nekop2p.LoanStatus" json:"status,omitempty"`
	ZkCreditProof []byte                 `protobuf:"bytes,7,opt,name=zk_credit_proof,json=zkCreditProof,proto3" json:"zk_credit_proof,omitempty"`
	InkwellParams []byte                 `protobuf:"bytes,8,opt,name=inkwell_params,json=inkwellParams,proto3" json:"inkwell_params,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DueDate       int64                  `protobuf:"varint,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	SettledAt     int64                  `protobuf:"varint,11,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	DeliveryProof []byte                 `protobuf:"bytes,12,opt,name=delivery_proof,json=deliveryProof,proto3" json:"delivery_proof,omitempty"`
	SettlementCmd []byte                 `protobuf:"bytes,13,opt,name=settlement_cmd,json=settlementCmd,proto3" json:"settlement_cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanRecord) Reset() {
	*x = LoanRecord{}
	mi := &file_nekop2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanRecord) ProtoMessage() {}

func (x *LoanRecord) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanRecord.ProtoReflect.Descriptor instead.
func (*LoanRecord) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{4}
}

func (x *LoanRecord) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *LoanRecord) GetBorrowerAnon() []byte {
	if x != nil {
		return x.BorrowerAnon
	}
	return nil
}

func (x *LoanRecord) GetLenderAnon() []byte {
	if x != nil {
		return x.LenderAnon
	}
	return nil
}

func (x *LoanRecord) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LoanRecord) GetTermDays() int64 {
	if x != nil {
		return x.TermDays
	}
	return 0
}

func (x *LoanRecord) GetStatus() LoanStatus {
	if x != nil {
		return x.Status
	}
	return LoanStatus_LOAN_PENDING
}

func (x *LoanRecord) GetZkCreditProof() []byte {
	if x != nil {
		return x.ZkCreditProof
	}
	return nil
}

func (x *LoanRecord) GetInkwellParams() []byte {
	if x != nil {
		return x.InkwellParams
	}
	return nil
}

func (x *LoanRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LoanRecord) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

func (x *LoanRecord) GetSettledAt() int64 {
	if x != nil {
		return x.SettledAt
	}
	return 0
}

func (x *LoanRecord) GetDeliveryProof() []byte {
	if x != nil {
		return x.DeliveryProof
	}
	return nil
}

func (x *LoanRecord) GetSettlementCmd() []byte {
	if x != nil {
		return x.SettlementCmd
	}
	return nil
}

type NodeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	RelayCount    uint64                 `protobuf:"varint,2,opt,name=relay_count,json=relayCount,proto3" json:"relay_count,omitempty"`
	OnlineBlocks  uint64                 `protobuf:"varint,3,opt,name=online_blocks,json=onlineBlocks,proto3" json:"online_blocks,omitempty"`
	TotalBlocks   uint64                 `protobuf:"varint,4,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	SalaryEarned  uint64                 `protobuf:"varint,5,opt,name=salary_earned,json=salaryEarned,proto3" json:"salary_earned,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	TermExpires   int64                  `protobuf:"varint,7,opt,name=term_expires,json=termExpires,proto3" json:"term_expires,omitempty"`
	ExamPassed    bool                   `protobuf:"varint,8,opt,name=exam_passed,json=examPassed,proto3" json:"exam_passed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_nekop2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStats) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *NodeStats) GetRelayCount() uint64 {
	if x != nil {
		return x.RelayCount
	}
	return 0
}

func (x *NodeStats) GetOnlineBlocks() uint64 {
	if x != nil {
		return x.OnlineBlocks
	}
	return 0
}

func (x *NodeStats) GetTotalBlocks() uint64 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *NodeStats) GetSalaryEarned() uint64 {
	if x != nil {
		return x.SalaryEarned
	}
	return 0
}

func (x *NodeStats) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *NodeStats) GetTermExpires() int64 {
	if x != nil {
		return x.TermExpires
	}
	return 0
}

func (x *NodeStats) GetExamPassed() bool {
	if x != nil {
		return x.ExamPassed
	}
	return false
}

type ExamResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	ExamType      ExamType               `protobuf:"varint,2,opt,name=exam_type,json=examType,proto3,enum=nekop2p.ExamType" json:"exam_type,omitempty"`
	Passed        bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	Score         uint64                 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ResultHash    []byte                 `protobuf:"bytes,6,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamResult) Reset() {
	*x = ExamResult{}
	mi := &file_nekop2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamResult) ProtoMessage() {}

func (x *ExamResult) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamResult.ProtoReflect.Descriptor instead.
func (*ExamResult) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{6}
}

func (x *ExamResult) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *ExamResult) GetExamType() ExamType {
	if x != nil {
		return x.ExamType
	}
	return ExamType_EXAM_RELAY
}

func (x *ExamResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ExamResult) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ExamResult) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *ExamResult) GetResultHash() []byte {
	if x != nil {
		return x.ResultHash
	}
	return nil
}

type MsgRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecvPk        []byte                 `protobuf:"bytes,1,opt,name=recv_pk,json=recvPk,proto3" json:"recv_pk,omitempty"`
	SendPk        []byte                 `protobuf:"bytes,2,opt,name=send_pk,json=sendPk,proto3" json:"send_pk,omitempty"`
	ZkProof       []byte                 `protobuf:"bytes,3,opt,name=zk_proof,json=zkProof,proto3" json:"zk_proof,omitempty"`
	GuarantorSigs [][]byte               `protobuf:"bytes,4,rep,name=guarantor_sigs,json=guarantorSigs,proto3" json:"guarantor_sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegister) Reset() {
	*x = MsgRegister{}
	mi := &file_nekop2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegister) ProtoMessage() {}

func (x *MsgRegister) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegister.ProtoReflect.Descriptor instead.
func (*MsgRegister) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{7}
}

func (x *MsgRegister) GetRecvPk() []byte {
	if x != nil {
		return x.RecvPk
	}
	return nil
}

func (x *MsgRegister) GetSendPk() []byte {
	if x != nil {
		return x.SendPk
	}
	return nil
}

func (x *MsgRegister) GetZkProof() []byte {
	if x != nil {
		return x.ZkProof
	}
	return nil
}

func (x *MsgRegister) GetGuarantorSigs() [][]byte {
	if x != nil {
		return x.GuarantorSigs
	}
	return nil
}

type MsgGuarantee struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Inviter         string                 `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee         string                 `protobuf:"bytes,2,opt,name=invitee,proto3" json:"invitee,omitempty"`
	BondCommitments [][]byte               `protobuf:"bytes,3,rep,name=bond_commitments,json=bondCommitments,proto3" json:"bond_commitments,omitempty"`
	Coefficient     uint64                 `protobuf:"varint,4,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgGuarantee) Reset() {
	*x = MsgGuarantee{}
	mi := &file_nekop2p_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGuarantee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGuarantee) ProtoMessage() {}

func (x *MsgGuarantee) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGuarantee.ProtoReflect.Descriptor instead.
func (*MsgGuarantee) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{8}
}

func (x *MsgGuarantee) GetInviter() string {
	if x != nil {
		return x.Inviter
	}
	return ""
}

func (x *MsgGuarantee) GetInvitee() string {
	if x != nil {
		return x.Invitee
	}
	return ""
}

func (x *MsgGuarantee) GetBondCommitments() [][]byte {
	if x != nil {
		return x.BondCommitments
	}
	return nil
}

func (x *MsgGuarantee) GetCoefficient() uint64 {
	if x != nil {
		return x.Coefficient
	}
	return 0
}

type MsgRepay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ZkRepayProof  []byte                 `protobuf:"bytes,3,opt,name=zk_repay_proof,json=zkRepayProof,proto3" json:"zk_repay_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRepay) Reset() {
	*x = MsgRepay{}
	mi := &file_nekop2p_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRepay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRepay) ProtoMessage() {}

func (x *MsgRepay) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRepay.ProtoReflect.Descriptor instead.
func (*MsgRepay) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{9}
}

func (x *MsgRepay) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MsgRepay) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MsgRepay) GetZkRepayProof() []byte {
	if x != nil {
		return x.ZkRepayProof
	}
	return nil
}

type MsgRequestLoan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BorrowerAnon  []byte                 `protobuf:"bytes,1,opt,name=borrower_anon,json=borrowerAnon,proto3" json:"borrower_anon,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TermDays      int64                  `protobuf:"varint,3,opt,name=term_days,json=termDays,proto3" json:"term_days,omitempty"`
	ZkCreditProof []byte                 `protobuf:"bytes,4,opt,name=zk_credit_proof,json=zkCreditProof,proto3" json:"zk_credit_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRequestLoan) Reset() {
	*x = MsgRequestLoan{}
	mi := &file_nekop2p_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRequestLoan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRequestLoan) ProtoMessage() {}

func (x *MsgRequestLoan) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRequestLoan.ProtoReflect.Descriptor instead.
func (*MsgRequestLoan) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{10}
}

func (x *MsgRequestLoan) GetBorrowerAnon() []byte {
	if x != nil {
		return x.BorrowerAnon
	}
	return nil
}

func (x *MsgRequestLoan) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MsgRequestLoan) GetTermDays() int64 {
	if x != nil {
		return x.TermDays
	}
	return 0
}

func (x *MsgRequestLoan) GetZkCreditProof() []byte {
	if x != nil {
		return x.ZkCreditProof
	}
	return nil
}

type MsgRegisterNode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeAddress    string                 `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Role           NodeRole               `protobuf:"varint,2,opt,name=role,proto3,enum=nekop2p.NodeRole" json:"role,omitempty"`
	ExamResultHash []byte                 `protobuf:"bytes,3,opt,name=exam_result_hash,json=examResultHash,proto3" json:"exam_result_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgRegisterNode) Reset() {
	*x = MsgRegisterNode{}
	mi := &file_nekop2p_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterNode) ProtoMessage() {}

func (x *MsgRegisterNode) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterNode.ProtoReflect.Descriptor instead.
func (*MsgRegisterNode) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{11}
}

func (x *MsgRegisterNode) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *MsgRegisterNode) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_NONE
}

func (x *MsgRegisterNode) GetExamResultHash() []byte {
	if x != nil {
		return x.ExamResultHash
	}
	return nil
}

type ChainSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHeight    int64                  `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight      int64                  `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSyncRequest) Reset() {
	*x = ChainSyncRequest{}
	mi := &file_nekop2p_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSyncRequest) ProtoMessage() {}

func (x *ChainSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSyncRequest.ProtoReflect.Descriptor instead.
func (*ChainSyncRequest) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{12}
}

func (x *ChainSyncRequest) GetFromHeight() int64 {
	if x != nil {
		return x.FromHeight
	}
	return 0
}

func (x *ChainSyncRequest) GetToHeight() int64 {
	if x != nil {
		return x.ToHeight
	}
	return 0
}

type ChainSyncBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSyncBlock) Reset() {
	*x = ChainSyncBlock{}
	mi := &file_nekop2p_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSyncBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSyncBlock) ProtoMessage() {}

func (x *ChainSyncBlock) ProtoReflect() protoreflect.Message {
	mi := &file_nekop2p_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSyncBlock.ProtoReflect.Descriptor instead.
func (*ChainSyncBlock) Descriptor() ([]byte, []int) {
	return file_nekop2p_proto_rawDescGZIP(), []int{13}
}

func (x *ChainSyncBlock) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChainSyncBlock) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ChainSyncBlock) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ChainSyncBlock) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_nekop2p_proto protoreflect.FileDescriptor

const file_nekop2p_proto_rawDesc = "" +
	"\n" +
	"\rnekop2p.proto\x12\anekop2p\"\xfe\x04\n" +
	"\tUserBlock\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\x04R\raccountNumber\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x17\n" +
	"\arecv_pk\x18\x04 \x01(\fR\x06recvPk\x12\x17\n" +
	"\asend_pk\x18\x05 \x01(\fR\x06sendPk\x12!\n" +
	"\fcredit_score\x18\x06 \x01(\x04R\vcreditScore\x12!\n" +
	"\ftrust_weight\x18\a \x01(\x04R\vtrustWeight\x12\x1f\n" +
	"\vtotal_repay\x18\b \x01(\x04R\n" +
	"totalRepay\x12!\n" +
	"\fcredit_limit\x18\t \x01(\x04R\vcreditLimit\x12\x1d\n" +
	"\n" +
	"seed_phase\x18\n" +
	" \x01(\bR\tseedPhase\x12\x1e\n" +
	"\n" +
	"guarantors\x18\v \x03(\fR\n" +
	"guarantors\x12.\n" +
	"\tnode_role\x18\f \x01(\x0e2\x11.nekop2p.NodeRoleR\bnodeRole\x12&\n" +
	"\x0fnode_term_start\x18\r \x01(\x03R\rnodeTermStart\x12\"\n" +
	"\rnode_term_end\x18\x0e \x01(\x03R\vnodeTermEnd\x12/\n" +
	"\afriends\x18\x0f \x03(\v2\x15.nekop2p.FriendRecordR\afriends\x125\n" +
	"\rguaranteed_of\x18\x10 \x03(\v2\x10.nekop2p.BondRefR\fguaranteedOf\x125\n" +
	"\rguaranteed_by\x18\x11 \x03(\v2\x10.nekop2p.BondRefR\fguaranteedBy\"\xba\x01\n" +
	"\fFriendRecord\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x17\n" +
	"\arecv_pk\x18\x02 \x01(\fR\x06recvPk\x12\x17\n" +
	"\asend_pk\x18\x03 \x01(\fR\x06sendPk\x12\x1d\n" +
	"\n" +
	"trust_dist\x18\x04 \x01(\rR\ttrustDist\x12\x19\n" +
	"\badded_at\x18\x05 \x01(\x03R\aaddedAt\x12#\n" +
	"\rintroduced_by\x18\x06 \x01(\fR\fintroducedBy\"C\n" +
	"\aBondRef\x12\x17\n" +
	"\abond_id\x18\x01 \x01(\tR\x06bondId\x12\x1f\n" +
	"\vother_party\x18\x02 \x01(\fR\n" +
	"otherParty\"\xd2\x02\n" +
	"\rGuaranteeBond\x12\x17\n" +
	"\abond_id\x18\x01 \x01(\tR\x06bondId\x12\x18\n" +
	"\ainviter\x18\x02 \x01(\fR\ainviter\x12\x18\n" +
	"\ainvitee\x18\x03 \x01(\fR\ainvitee\x12-\n" +
	"\x12locked_commitments\x18\x04 \x03(\fR\x11lockedCommitments\x12\x1d\n" +
	"\n" +
	"total_bond\x18\x05 \x01(\x04R\ttotalBond\x12 \n" +
	"\vcoefficient\x18\x06 \x01(\x04R\vcoefficient\x12\x1d\n" +
	"\n" +
	"seed_limit\x18\a \x01(\x04R\tseedLimit\x12\x1b\n" +
	"\tlocked_at\x18\b \x01(\x03R\blockedAt\x12\x1b\n" +
	"\tunlock_at\x18\t \x01(\x03R\bunlockAt\x12+\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x13.nekop2p.BondStatusR\x06status\"\xc3\x03\n" +
	"\n" +
	"LoanRecord\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12#\n" +
	"\rborrower_anon\x18\x02 \x01(\fR\fborrowerAnon\x12\x1f\n" +
	"\vlender_anon\x18\x03 \x01(\fR\n" +
	"lenderAnon\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x1b\n" +
	"\tterm_days\x18\x05 \x01(\x03R\btermDays\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.nekop2p.LoanStatusR\x06status\x12&\n" +
	"\x0fzk_credit_proof\x18\a \x01(\fR\rzkCreditProof\x12%\n" +
	"\x0einkwell_params\x18\b \x01(\fR\rinkwellParams\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x19\n" +
	"\bdue_date\x18\n" +
	" \x01(\x03R\adueDate\x12\x1d\n" +
	"\n" +
	"settled_at\x18\v \x01(\x03R\tsettledAt\x12%\n" +
	"\x0edelivery_proof\x18\f \x01(\fR\rdeliveryProof\x12%\n" +
	"\x0esettlement_cmd\x18\r \x01(\fR\rsettlementCmd\"\x9d\x02\n" +
	"\tNodeStats\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1f\n" +
	"\vrelay_count\x18\x02 \x01(\x04R\n" +
	"relayCount\x12#\n" +
	"\ronline_blocks\x18\x03 \x01(\x04R\fonlineBlocks\x12!\n" +
	"\ftotal_blocks\x18\x04 \x01(\x04R\vtotalBlocks\x12#\n" +
	"\rsalary_earned\x18\x05 \x01(\x04R\fsalaryEarned\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12!\n" +
	"\fterm_expires\x18\a \x01(\x03R\vtermExpires\x12\x1f\n" +
	"\vexam_passed\x18\b \x01(\bR\n" +
	"examPassed\"\xd1\x01\n" +
	"\n" +
	"ExamResult\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12.\n" +
	"\texam_type\x18\x02 \x01(\x0e2\x11.nekop2p.ExamTypeR\bexamType\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x04R\x05score\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x03R\vcompletedAt\x12\x1f\n" +
	"\vresult_hash\x18\x06 \x01(\fR\n" +
	"resultHash\"\x81\x01\n" +
	"\vMsgRegister\x12\x17\n" +
	"\arecv_pk\x18\x01 \x01(\fR\x06recvPk\x12\x17\n" +
	"\asend_pk\x18\x02 \x01(\fR\x06sendPk\x12\x19\n" +
	"\bzk_proof\x18\x03 \x01(\fR\azkProof\x12%\n" +
	"\x0eguarantor_sigs\x18\x04 \x03(\fR\rguarantorSigs\"\x8f\x01\n" +
	"\fMsgGuarantee\x12\x18\n" +
	"\ainviter\x18\x01 \x01(\tR\ainviter\x12\x18\n" +
	"\ainvitee\x18\x02 \x01(\tR\ainvitee\x12)\n" +
	"\x10bond_commitments\x18\x03 \x03(\fR\x0fbondCommitments\x12 \n" +
	"\vcoefficient\x18\x04 \x01(\x04R\vcoefficient\"\\\n" +
	"\bMsgRepay\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12$\n" +
	"\x0ezk_repay_proof\x18\x03 \x01(\fR\fzkRepayProof\"\x92\x01\n" +
	"\x0eMsgRequestLoan\x12#\n" +
	"\rborrower_anon\x18\x01 \x01(\fR\fborrowerAnon\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1b\n" +
	"\tterm_days\x18\x03 \x01(\x03R\btermDays\x12&\n" +
	"\x0fzk_credit_proof\x18\x04 \x01(\fR\rzkCreditProof\"\x85\x01\n" +
	"\x0fMsgRegisterNode\x12!\n" +
	"\fnode_address\x18\x01 \x01(\tR\vnodeAddress\x12%\n" +
	"\x04role\x18\x02 \x01(\x0e2\x11.nekop2p.NodeRoleR\x04role\x12(\n" +
	"\x10exam_result_hash\x18\x03 \x01(\fR\x0eexamResultHash\"P\n" +
	"\x10ChainSyncRequest\x12\x1f\n" +
	"\vfrom_height\x18\x01 \x01(\x03R\n" +
	"fromHeight\x12\x1b\n" +
	"\tto_height\x18\x02 \x01(\x03R\btoHeight\"\x89\x01\n" +
	"\x0eChainSyncBlock\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12\"\n" +
	"\ftransactions\x18\x03 \x03(\fR\ftransactions\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*]\n" +
	"\bNodeRole\x12\r\n" +
	"\tNODE_NONE\x10\x00\x12\x0f\n" +
	"\vNODE_PUBLIC\x10\x01\x12\x17\n" +
	"\x13NODE_OFFICIAL_RELAY\x10\x02\x12\x18\n" +
	"\x14NODE_OFFICIAL_RECORD\x10\x03*D\n" +
	"\n" +
	"BondStatus\x12\x0f\n" +
	"\vBOND_ACTIVE\x10\x00\x12\x11\n" +
	"\rBOND_RELEASED\x10\x01\x12\x12\n" +
	"\x0eBOND_FORFEITED\x10\x02*U\n" +
	"\n" +
	"LoanStatus\x12\x10\n" +
	"\fLOAN_PENDING\x10\x00\x12\x0f\n" +
	"\vLOAN_ACTIVE\x10\x01\x12\x10\n" +
	"\fLOAN_SETTLED\x10\x02\x12\x12\n" +
	"\x0eLOAN_DEFAULTED\x10\x03*+\n" +
	"\bExamType\x12\x0e\n" +
	"\n" +
	"EXAM_RELAY\x10\x00\x12\x0f\n" +
	"\vEXAM_RECORD\x10\x01B*Z(github.com/nekop2p/nekop2p/proto/nekop2pb\x06proto3"

var (
	file_nekop2p_proto_rawDescOnce sync.Once
	file_nekop2p_proto_rawDescData []byte
)

func file_nekop2p_proto_rawDescGZIP() []byte {
	file_nekop2p_proto_rawDescOnce.Do(func() {
		file_nekop2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nekop2p_proto_rawDesc), len(file_nekop2p_proto_rawDesc)))
	})
	return file_nekop2p_proto_rawDescData
}

var file_nekop2p_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_nekop2p_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_nekop2p_proto_goTypes = []any{
	(NodeRole)(0),            // 0: nekop2p.NodeRole
	(BondStatus)(0),          // 1: nekop2p.BondStatus
	(LoanStatus)(0),          // 2: nekop2p.LoanStatus
	(ExamType)(0),            // 3: nekop2p.ExamType
	(*UserBlock)(nil),        // 4: nekop2p.UserBlock
	(*FriendRecord)(nil),     // 5: nekop2p.FriendRecord
	(*BondRef)(nil),          // 6: nekop2p.BondRef
	(*GuaranteeBond)(nil),    // 7: nekop2p.GuaranteeBond
	(*LoanRecord)(nil),       // 8: nekop2p.LoanRecord
	(*NodeStats)(nil),        // 9: nekop2p.NodeStats
	(*ExamResult)(nil),       // 10: nekop2p.ExamResult
	(*MsgRegister)(nil),      // 11: nekop2p.MsgRegister
	(*MsgGuarantee)(nil),     // 12: nekop2p.MsgGuarantee
	(*MsgRepay)(nil),         // 13: nekop2p.MsgRepay
	(*MsgRequestLoan)(nil),   // 14: nekop2p.MsgRequestLoan
	(*MsgRegisterNode)(nil),  // 15: nekop2p.MsgRegisterNode
	(*ChainSyncRequest)(nil), // 16: nekop2p.ChainSyncRequest
	(*ChainSyncBlock)(nil),   // 17: nekop2p.ChainSyncBlock
}
var file_nekop2p_proto_depIdxs = []int32{
	0, // 0: nekop2p.UserBlock.node_role:type_name -> nekop2p.NodeRole
	5, // 1: nekop2p.UserBlock.friends:type_name -> nekop2p.FriendRecord
	6, // 2: nekop2p.UserBlock.guaranteed_of:type_name -> nekop2p.BondRef
	6, // 3: nekop2p.UserBlock.guaranteed_by:type_name -> nekop2p.BondRef
	1, // 4: nekop2p.GuaranteeBond.status:type_name -> nekop2p.BondStatus
	2, // 5: nekop2p.LoanRecord.status:type_name -> nekop2p.LoanStatus
	3, // 6: nekop2p.ExamResult.exam_type:type_name -> nekop2p.ExamType
	0, // 7: nekop2p.MsgRegisterNode.role:type_name -> nekop2p.NodeRole
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_nekop2p_proto_init() }
func file_nekop2p_proto_init() {
	if File_nekop2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nekop2p_proto_rawDesc), len(file_nekop2p_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nekop2p_proto_goTypes,
		DependencyIndexes: file_nekop2p_proto_depIdxs,
		EnumInfos:         file_nekop2p_proto_enumTypes,
		MessageInfos:      file_nekop2p_proto_msgTypes,
	}.Build()
	File_nekop2p_proto = out.File
	file_nekop2p_proto_goTypes = nil
	file_nekop2p_proto_depIdxs = nil
}
